# Generated by Django 5.2.7 on 2025-10-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ica', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('frecuencia_aplicacion', models.PositiveIntegerField(help_text='Dias entre aplicaciones')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('HONGO', 'Aplicacion Hongo'), ('PLAGA', 'Aplicacion Plaga'), ('FERTILIZANTE', 'Aplicacion Fertilizante'), ('OTRA', 'Otra Labor')], max_length=20)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlFertilizante',
            fields=[
                ('productocontrol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.productocontrol')),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
            ],
            bases=('management.productocontrol',),
        ),
        migrations.CreateModel(
            name='ControlHongo',
            fields=[
                ('productocontrol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.productocontrol')),
                ('periodo_carencia', models.PositiveIntegerField(help_text='Dias de carencia')),
                ('nombre_hongo', models.CharField(max_length=200)),
            ],
            bases=('management.productocontrol',),
        ),
        migrations.CreateModel(
            name='ControlPlaga',
            fields=[
                ('productocontrol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.productocontrol')),
                ('periodo_carencia', models.PositiveIntegerField(help_text='Dias de carencia')),
            ],
            bases=('management.productocontrol',),
        ),
        migrations.CreateModel(
            name='LaborProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aplicacion', models.DateField()),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_usados', to='management.labor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores_asociadas', to='management.productocontrol')),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_catastro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=200)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='management.productor')),
            ],
            options={
                'unique_together': {('productor', 'numero_catastro')},
            },
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('tipo_cultivo', models.CharField(max_length=200)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viveros', to='management.finca')),
            ],
            options={
                'unique_together': {('finca', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='labor',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='management.vivero'),
        ),
    ]
